121 check col names
ONSdigital/research-and-development pull request #22
Opened 2023-05-04 08:40 UTC by RoddyMacrae

## Pull Request submission

*Insert detailed bullet points about your changes here!*

- Branch 121 has two additional functions in validation.py compared to 120.
- check_var_names() and data_key_diffs()
- check_var_names() does a one-to-one matching of the keys in the data dictionary and the schema dictionary. If they match it returns True, otherwise it returns False
- data_key_diffs() gives a more meaningful difference between the two dictionaries and uses the module deepdiff to do so.
- A dictionary containing only the keys from the schema dictionary is created and then compared to the data headers dictionary.
- The comparison is done case sensitively be including of 'ignore_string_case=False' in the DeepDiff() call.
- The output of data_key_diffs() is a dictionary containing two key-value pairs. The first is 'dictionary_item_added' with a list value containing the differences in column names in the data file, these should be fixed to match the schema file columns. There should be no items in the value list ideally. The second is 'dictionary_item_removed' with a list value containing the columns missing from the data file (present in the schema file). These items need to be added to the data file.

*Insert any instructions to help the reviewer, e.g. "install new requirements from `environment.yml`"*

- Make sure requirements are up-to-date as with branch 120.
- Need to make sure deepdiff is installed: 'pip install deepdiff' (!!! Need to make sure your pip is updated to latest version available or this won't work !!!)

*Let the reviewer know what data files are needed (and if applicable, where they are to be found)

- Data files should be linked to relevant areas on DAP and to relevant files in config/ directory as defaults.

#### Closes or fixes

* Detail the ticket(s) you are closing with this PR
Closes #
RDRP-121: https://jira.ons.gov.uk/browse/RDRP-121

#### Code

- [x] **Code runs** The code runs on my machine and/or CDSW
- [ ] **Conflicts resolved** There are no conflicts (I have performed a rebase if necessary)
- [x] **Requirements** My/our code functions according to the requirements of the ticket
- [x] **Dependencies** I have updated the environment yaml so it includes any new libraries I have used
- [x] **Configuration file updated** any high level parameters that the user may interact with have been put into the config file (and imported to the script)
- [x] **Clean Code**
    - [x] Code is as [PEP 8]([url](https://peps.python.org/pep-0008/)) compliant as I can humanly make it
    - [x] Code passess flake8 linting check
    - [x] Code adheres to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
- [x] **Type hints** All new functions have [type hints ](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)

#### Documentation

Any new code includes all the following forms of documentation:

- [x] **Function Documentation** Docstrings within the function(s')/methods have been created
    - [x] Includes `Args` and `returns` for all major functions
    - [x] The docstring details data types
- [ ] **Updated Documentation**: User and/or developer working doc has been updated

#### Data
- [x] All data needed to run this script is available in Dev/Test
- [x] All data is excluded from this pull request
- [x] Secrets checker pre-commit passes

#### Testing
- [x] **Unit tests** Unit tests have been created and are passing _or a new ticket to create tests has been created_

---

# Peer Review Section

- [ ] All requirements install from (updated) `environment.yaml`
- [ ] Documentation has been created and is clear - **check the working document**
- [ ] Doctrings ([Google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) have been created and accurately describe the function's functionality
- [ ] Unit tests pass, or if not present _a new ticket to create tests has been created_
- [ ] **Code runs** The code runs on reviewer's machine and/or CDSW

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

---

### Review comments

*Insert detailed comments here!*

These might include, but not exclusively:

- bugs that need fixing (does it work as expected? and does it work with other code
  that it is likely to interact with?)
- alternative methods (could it be written more efficiently or with more clarity?)
- documentation improvements (does the documentation reflect how the code actually works?)
- additional tests that should be implemented (do the tests effectively assure that it
  works correctly?)
- code style improvements (could the code be written more clearly?)
- Do the changes represent a change in functionality so the version number should increase? Start a discussion if so.
- As a review you can generates the same outputs from running the code

Your suggestions should be tailored to the code that you are reviewing.
Be critical and clear, but not mean. Ask questions and set actions.

2023-06-06 18:05 UTC, jwestw requested changes
Github actions are failing due to import of deepdiff. Why is this? Can it be resolved?

2023-06-06 18:05 UTC, jwestw commented on src/data_validation/validation.py
> +        filePath -- _description_ (default: {"./config/Data_Schema.toml"})
"_description_ " is where you add a description. Please add one.

2023-06-28 17:40 UTC, smithv1 commented
Code looks good on check_var_names and data_key_diffs. Would like to discuss unit tests as I haven't used this method of creating args data before @jwestw @okudum

2023-06-29 16:02 UTC, smithv1 approved these changes

2023-06-29 16:02 UTC, smithv1 commented on tests/test_data_validation/test_validation.py
> +def test_data_key_diffs(tmp_path, test_data_df, test_data_dict):
This could be within a class and then have functions within that class to define test inputs. I can demo what I mean and apply to future examples and then merge this for now as is

2023-07-11 10:31 UTC, okudum approved these changes
The code looks good, the conflicts has been handled, and it is ready for merging.

2023-07-12 11:12 UTC, jwestw commented on tests/test_data_validation/test_validation.py
> +def test_data_key_diffs(tmp_path, test_data_df, test_data_dict):
Will merge as is for now.

2023-07-12 11:13 UTC, jwestw approved these changes

2023-07-12 11:13 UTC, merged