RDRP-860 join cellno mapper in mapping module
ONSdigital/research-and-development pull request #268
Opened 2024-07-12 16:25 UTC by AnneONS

## Pull Request submission

*Insert detailed bullet points about your changes here!*

*Insert any instructions to help the reviewer, e.g. "install new requirements from `requirements.txt`"*

*Let the reviewer know what data files are needed (and if applicable, where they are to be found)

#### Closes or fixes

* Detail the ticket(s) you are closing with this PR
Closes #

#### Code

- [ ] **Code runs** The code runs on my machine and/or CDSW
- [ ] **Conflicts resolved** There are no conflicts (I have performed a rebase if necessary)
- [ ] **Requirements** My/our code functions according to the requirements of the ticket
- [ ] **Dependencies** I have updated the environment yaml so it includes any new libraries I have used
- [ ] **Configuration file updated** any high level parameters that the user may interact with have been put into the config file (and imported to the script)
- [ ] **Clean Code**
    - [ ] Code is as [PEP 8]([url](https://peps.python.org/pep-0008/)) compliant as I can humanly make it
    - [ ] Code passess flake8 linting check
    - [ ] Code adheres to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
- [ ] **Type hints** All new functions have [type hints ](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)

#### Documentation

Any new code includes all the following forms of documentation:

- [ ] **Function Documentation** Docstrings within the function(s')/methods have been created
    - [ ] Includes `Args` and `returns` for all major functions
    - [ ] The docstring details data types
- [ ] **Updated Documentation**: User and/or developer working doc has been updated

#### Data
- [ ] All data needed to run this script is available in Dev/Test
- [ ] All data is excluded from this pull request
- [ ] Secrets checker pre-commit passes

#### Testing
- [ ] **Unit tests** Unit tests have been created and are passing _or a new ticket to create tests has been created_

---

# Peer Review Section

- [ ] All requirements install from (updated) `requirements.txt`
- [ ] Documentation has been created and is clear - **check the working document**
- [ ] Doctrings ([Google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) have been created and accurately describe the function's functionality
- [ ] Unit tests pass, or if not present _a new ticket to create tests has been created_
- [ ] **Code runs** The code runs on reviewer's machine and/or CDSW

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

---

### Review comments

*Insert detailed comments here!*

These might include, but not exclusively:

- bugs that need fixing (does it work as expected? and does it work with other code
  that it is likely to interact with?)
- alternative methods (could it be written more efficiently or with more clarity?)
- documentation improvements (does the documentation reflect how the code actually works?)
- additional tests that should be implemented (do the tests effectively assure that it
  works correctly?)
- code style improvements (could the code be written more clearly?)
- Do the changes represent a change in functionality so the version number should increase? Start a discussion if so.
- As a review you can generates the same outputs from running the code

Your suggestions should be tailored to the code that you are reviewing.
Be critical and clear, but not mean. Ask questions and set actions.

2024-07-15 11:10 UTC, CBROWN-ONS requested changes
Hi @AnneONS . There's a few comments here, mostly small.

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/cellno_mapping.py
> +    """
incorrect docstring formatting - should be tabbed in aftert section title.

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/cellno_mapping.py
> +    """
incorrect docstring formatting

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/cellno_mapping.py
> +    """
incorrect docstring formatting

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/cellno_mapping.py
> +def check_expected_number_of_cellnumbers(cellno_df: pd.DataFrame, num: int) -> None:
This is only called once, and doesn't do anything really (simple length check and error raise). This could be moved out of a function.

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/cellno_mapping.py
> +def check_cellno_range(cellno_df: pd.DataFrame) -> None:
Same as the above function

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/cellno_mapping.py
> +    """
Incorrect docstring format

2024-07-15 11:10 UTC, cbrowning04 commented on src/estimation/estimation_main.py
> +    # cell_unit_dict = cmap.cellno_unit_dict(cellno_df)
Happy for this to be fully removed.

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/cellno_mapping.py
> +"""Return a dictionary for the cell_no mapper"""
Inaccurate file description here.

1. The 'main' function from this returns a df.
2. There are multiple functions in this file, therefore the description should adhere to each of them.
3. Small thing, but can a period be added to the end of the decription for consistency.

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/mapping_helpers.py
> +    on_col: str,
Not too fussed about this since `on_col` is quite descriptive, however maybe `join_col` would be better here

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/mapping_helpers.py
> +    """
Docstring missing items
1. Args (some)
2. Raises

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/mapping_helpers.py
> +    check_col: str,
This argument is unused - please remove

2024-07-15 11:10 UTC, cbrowning04 commented on src/mapping/mapping_helpers.py
>      col_to_check (str): The name of the column to check.
This docstring appears to be incorrectly formatted (not tabbed in after section title)

2024-07-15 11:10 UTC, cbrowning04 commented on src/staging/staging_helpers.py
>      full_responses (pd.DataFrame): The DataFrame containing the data to be
docstring formatting

2024-07-15 11:10 UTC, cbrowning04 commented on src/staging/validation.py
>      Returns:
docstring formatting

2024-07-15 11:10 UTC, CBROWN-ONS commented on src/estimation/calculate_weights.py
> +    """Calculate the 'a' weighting factor for a cell group.
Maybe add a description of the formula here?

2024-07-15 11:34 UTC, AnneONS commented on src/mapping/cellno_mapping.py
> +    """
good shout, corrected these

2024-07-15 12:01 UTC, AnneONS commented on src/mapping/cellno_mapping.py
> +def check_expected_number_of_cellnumbers(cellno_df: pd.DataFrame, num: int) -> None:
ok I've changed this.

2024-07-15 12:01 UTC, AnneONS commented on src/mapping/cellno_mapping.py
> +def check_cellno_range(cellno_df: pd.DataFrame) -> None:
ok I've changed this.

2024-07-15 12:09 UTC, AnneONS commented on src/mapping/mapping_helpers.py
> +    check_col: str,
good spot, removed.

2024-07-15 13:01 UTC, AnneONS commented on tests/test_estimation/test_calculate_weights.py
> +            [1, 1, "P", "210", "0006", 0, 1, 10, False, 10.0],
@CBROWN-ONS  it's infuriating that the pre-commits do this: noqa doesn't work in the tests as it does in src. What can we do to allow > 88 line lengths in tests?

2024-07-16 09:19 UTC, cbrowning04 commented on tests/test_estimation/test_calculate_weights.py
> +            [1, 1, "P", "210", "0006", 0, 1, 10, False, 10.0],
We could potentially exclude the test files from the pre-commit

2024-07-16 09:19 UTC, cbrowning04 approved these changes

2024-07-16 09:20 UTC, CBROWN-ONS commented
HI @AnneONS . I'm happy with the changes and happy for this to be merged.

2024-07-16 11:52 UTC, merged