RDRP-1081- pnp 2021 backdata prep: fix the move to instance 1
ONSdigital/research-and-development pull request #392
Opened 2024-12-17 10:05 UTC by AnneONS

## Pull Request submission

This PR contains code to fix the function which moves values for the 2xx and 3xx cols from instance 0 to instance 1, and replace the values in instance 0 with zeros.

It was also necessary to ensure that an instance 1 is created if one doesn't exist yet for a reference.

A unit test has been included to check this is working as it should

In addition, a very good investigation comparing the outputs to the raw data is needed.

Closes #1081

#### Code

- [ ] **Code runs** The code runs on my machine and/or CDSW
- [ ] **Conflicts resolved** There are no conflicts (I have performed a rebase if necessary)
- [ ] **Requirements** My/our code functions according to the requirements of the ticket
- [ ] **Dependencies** I have updated the environment yaml so it includes any new libraries I have used
- [ ] **Configuration file updated** any high level parameters that the user may interact with have been put into the config file (and imported to the script)
- [ ] **Clean Code**
    - [ ] Code is as [PEP 8]([url](https://peps.python.org/pep-0008/)) compliant as I can humanly make it
    - [ ] Code passess flake8 linting check
    - [ ] Code adheres to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
- [ ] **Type hints** All new functions have [type hints ](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)

#### Documentation

Any new code includes all the following forms of documentation:

- [ ] **Function Documentation** Docstrings within the function(s')/methods have been created
    - [ ] Includes `Args` and `returns` for all major functions
    - [ ] The docstring details data types
- [ ] **Updated Documentation**: User and/or developer working doc has been updated

#### Data
- [ ] All data needed to run this script is available in Dev/Test
- [ ] All data is excluded from this pull request
- [ ] Secrets checker pre-commit passes

#### Testing
- [ ] **Unit tests** Unit tests have been created and are passing _or a new ticket to create tests has been created_

---

# Peer Review Section

- [ ] All requirements install from (updated) `requirements.txt`
- [ ] Documentation has been created and is clear - **check the working document**
- [ ] Doctrings ([Google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) have been created and accurately describe the function's functionality
- [ ] Unit tests pass, or if not present _a new ticket to create tests has been created_
- [ ] **Code runs** The code runs on reviewer's machine and/or CDSW

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

---

### Review comments

*Insert detailed comments here!*

These might include, but not exclusively:

- bugs that need fixing (does it work as expected? and does it work with other code
  that it is likely to interact with?)
- alternative methods (could it be written more efficiently or with more clarity?)
- documentation improvements (does the documentation reflect how the code actually works?)
- additional tests that should be implemented (do the tests effectively assure that it
  works correctly?)
- code style improvements (could the code be written more clearly?)
- Do the changes represent a change in functionality so the version number should increase? Start a discussion if so.
- As a review you can generates the same outputs from running the code

Your suggestions should be tailored to the code that you are reviewing.
Be critical and clear, but not mean. Ask questions and set actions.

2024-12-18 11:10 UTC, Ryan2Y79 requested changes, later dismissed
Its great you added a unit test for `populate_instance_1_columns` :D 

Just 2 comments to address. Cheers.

2024-12-18 11:10 UTC, Ryan2Y79 commented on helpers/create_pnp_backdata.py
> -    backdata_in_path = config["imputation_paths"]["backdata_in_path"]
Can we now remove this config value as it not redundant: `config["imputation_paths"]["backdata_in_path"]`.

2024-12-18 11:10 UTC, Ryan2Y79 commented on helpers/create_pnp_backdata.py
> +    merged_df = pd.merge(df, update_df, on=["reference", "instance"], how="left", suffixes=("", "_y"))
Can we please have this line over several, to not exceed the character limit per line. Cheers.

2024-12-18 11:21 UTC, AnneONS commented on helpers/create_pnp_backdata.py
> -    backdata_in_path = config["imputation_paths"]["backdata_in_path"]
yes, I've now removed it from the dev_config.

2024-12-18 17:22 UTC, Ryan2Y79 commented
@AnneONS According to `D:\research-and-development\config\backdata_schema.toml` the `604` column needs to be in float format, and not populated with strings! This is the ONLY schema issue with the PNP backdata.

2024-12-23 11:11 UTC, adriano-lopresti approved these changes
I am happy with the changes - PR ready to be merged

2025-01-06 11:30 UTC, merged