302 auto outliers
ONSdigital/research-and-development pull request #53
Opened 2023-08-03 11:36 UTC by AnneONS

## Pull Request submission

*Insert detailed bullet points about your changes here!*

*Insert any instructions to help the reviewer, e.g. "install new requirements from `environment.yml`"*

*Let the reviewer know what data files are needed (and if applicable, where they are to be found)

#### Closes or fixes

* Detail the ticket(s) you are closing with this PR
Closes #

#### Code

- [ ] **Code runs** The code runs on my machine and/or CDSW
- [ ] **Conflicts resolved** There are no conflicts (I have performed a rebase if necessary)
- [ ] **Requirements** My/our code functions according to the requirements of the ticket
- [ ] **Dependencies** I have updated the environment yaml so it includes any new libraries I have used
- [ ] **Configuration file updated** any high level parameters that the user may interact with have been put into the config file (and imported to the script)
- [ ] **Clean Code**
    - [ ] Code is as [PEP 8]([url](https://peps.python.org/pep-0008/)) compliant as I can humanly make it
    - [ ] Code passess flake8 linting check
    - [ ] Code adheres to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
- [ ] **Type hints** All new functions have [type hints ](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)

#### Documentation

Any new code includes all the following forms of documentation:

- [ ] **Function Documentation** Docstrings within the function(s')/methods have been created
    - [ ] Includes `Args` and `returns` for all major functions
    - [ ] The docstring details data types
- [ ] **Updated Documentation**: User and/or developer working doc has been updated

#### Data
- [ ] All data needed to run this script is available in Dev/Test
- [ ] All data is excluded from this pull request
- [ ] Secrets checker pre-commit passes

#### Testing
- [ ] **Unit tests** Unit tests have been created and are passing _or a new ticket to create tests has been created_

---

# Peer Review Section

- [ ] All requirements install from (updated) `environment.yaml`
- [ ] Documentation has been created and is clear - **check the working document**
- [ ] Doctrings ([Google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) have been created and accurately describe the function's functionality
- [ ] Unit tests pass, or if not present _a new ticket to create tests has been created_
- [ ] **Code runs** The code runs on reviewer's machine and/or CDSW

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

---

### Review comments

*Insert detailed comments here!*

These might include, but not exclusively:

- bugs that need fixing (does it work as expected? and does it work with other code
  that it is likely to interact with?)
- alternative methods (could it be written more efficiently or with more clarity?)
- documentation improvements (does the documentation reflect how the code actually works?)
- additional tests that should be implemented (do the tests effectively assure that it
  works correctly?)
- code style improvements (could the code be written more clearly?)
- Do the changes represent a change in functionality so the version number should increase? Start a discussion if so.
- As a review you can generates the same outputs from running the code

Your suggestions should be tailored to the code that you are reviewing.
Be critical and clear, but not mean. Ask questions and set actions.

2023-08-08 13:42 UTC, smithv1 requested changes

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +    args:
Capitalise the args to Args? Also Arguments or Args?

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +        OutlierMainLogger.error("upper_clip and lower_clip cannot be negative")
preference for a : or a -- for the args (-- is used elsewhere in pipeline e.g. validation.py)?

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +        upper_clip (float): The percentage for upper clipping as float
Put types in the doc strings in () or not? ("df -- DataFrame containing contributor data" or df (pd.DataFrame))

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +        OutlierMainLogger.error("upper_clip and lower_clip must sum to < 1")
<= within the error message?

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +        OutlierMainLogger.error("upper_clip and lower_clip must sum to < 1")
so change "OutlierMainLogger.error("upper_clip and lower_clip must sum to < 1")" 
to: "OutlierMainLogger.error("upper_clip and lower_clip must sum to <= 1")"?

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +):
add the return type hint and elsewhere where needed.

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +    filter_cond = (df[value_col] > 0) & (df.selectiontype=='P')
can we add the column name value_col to args? Also consistency check: do we prefer check df.column_name or df['column_name']?

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +
maybe add a comment here describe what next lines are doing and what interpolation="nearest" does

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +    quantiles_up = (
58 to 76: could this be one function called twice - what are the limits of functionising?

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +    quantiles_up = quantiles_up.rename(columns={value_col: "upper_band"})[
not sure what the second half of this is doing when reading - could add comment.

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +        value_col (str): The name of the column outliers are calculated for
change value_col to outlier_val_col

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +    Notes:
Notes, Args, Returns calitalised here - consistency check

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +            where 'seclectiontype' = 'P'.
'seclectiontype' = 'P'. - add further explanation?

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +    outlier_val_col = "709"
Maybe add outlier_val_col as an arg?

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +    df[outlier_val_col] = pd.to_numeric(df[outlier_val_col], errors='coerce')
Could add explanation of errors='coerce'

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/auto_outliers.py
> +    groupby_cols = ["period", "cellnumber"]
Add groupby_cols as arg?

2023-08-08 13:42 UTC, smithv1 commented on src/outlier_detection/outlier_main.py
> +    if config["global"]["network_or_hdfs"] == "network":
Do we not want this or similar to also run when set to hdfs

2023-08-08 15:12 UTC, AnneONS commented on src/outlier_detection/auto_outliers.py
> +):
Good point, I forgot that!

2023-08-08 15:13 UTC, AnneONS commented on src/outlier_detection/auto_outliers.py
> +            where 'seclectiontype' = 'P'.
Yes, I can do this know that I know more.

2023-08-08 15:19 UTC, AnneONS commented on src/outlier_detection/auto_outliers.py
> +        OutlierMainLogger.error("upper_clip and lower_clip must sum to < 1")
Thanks for spotting that, should have the logical condition upper_clip + lower_clip >= 1

2023-08-08 15:20 UTC, AnneONS commented on src/outlier_detection/auto_outliers.py
> +    outlier_val_col = "709"
Good point, I'll look at doing this.

2023-08-08 15:26 UTC, AnneONS commented on src/outlier_detection/outlier_main.py
> +    if config["global"]["network_or_hdfs"] == "network":
At this stage not sure how we are outputting files in hdfs

2023-08-11 15:19 UTC, smithv1 approved these changes

2023-08-11 15:20 UTC, smithv1 commented
Code looks good, tests good and runs via main.py

2023-08-16 11:24 UTC, jwestw approved these changes
This looks really good. Excellent code @AnneONS

2023-08-16 11:26 UTC, merged