Formatting postcodes
ONSdigital/research-and-development pull request #73
Opened 2023-08-24 15:24 UTC by ali-i3

## Pull Request submission

Fixing the issues we had with the postcode validation.
1) Fixed instances of correct postcodes being marked as incorrect
2) Output is now 2 csv files with reference and instance as lookup columns:
- A csv with incorrect pattern postcodes
- A csv with postcodes not in list
3) The pipeline doesn't fail if the postcodes are wrong, it instead outputs a file of incorrect postcodes. (Can be re-evaluated)

*Insert any instructions to help the reviewer, e.g. "install new requirements from `environment.yml`"*

*Let the reviewer know what data files are needed (and if applicable, where they are to be found)

#### Closes or fixes

* Detail the ticket(s) you are closing with this PR
Closes #

#### Code

- [ ] **Code runs** The code runs on my machine and/or CDSW
- [ ] **Conflicts resolved** There are no conflicts (I have performed a rebase if necessary)
- [ ] **Requirements** My/our code functions according to the requirements of the ticket
- [ ] **Dependencies** I have updated the environment yaml so it includes any new libraries I have used
- [ ] **Configuration file updated** any high level parameters that the user may interact with have been put into the config file (and imported to the script)
- [ ] **Clean Code**
    - [ ] Code is as [PEP 8]([url](https://peps.python.org/pep-0008/)) compliant as I can humanly make it
    - [ ] Code passess flake8 linting check
    - [ ] Code adheres to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
- [ ] **Type hints** All new functions have [type hints ](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)

#### Documentation

Any new code includes all the following forms of documentation:

- [ ] **Function Documentation** Docstrings within the function(s')/methods have been created
    - [ ] Includes `Args` and `returns` for all major functions
    - [ ] The docstring details data types
- [ ] **Updated Documentation**: User and/or developer working doc has been updated

#### Data
- [ ] All data needed to run this script is available in Dev/Test
- [ ] All data is excluded from this pull request
- [ ] Secrets checker pre-commit passes

#### Testing
- [ ] **Unit tests** Unit tests have been created and are passing _or a new ticket to create tests has been created_

---

# Peer Review Section

- [ ] All requirements install from (updated) `environment.yaml`
- [ ] Documentation has been created and is clear - **check the working document**
- [ ] Doctrings ([Google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) have been created and accurately describe the function's functionality
- [ ] Unit tests pass, or if not present _a new ticket to create tests has been created_
- [ ] **Code runs** The code runs on reviewer's machine and/or CDSW

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

---

### Review comments

*Insert detailed comments here!*

These might include, but not exclusively:

- bugs that need fixing (does it work as expected? and does it work with other code
  that it is likely to interact with?)
- alternative methods (could it be written more efficiently or with more clarity?)
- documentation improvements (does the documentation reflect how the code actually works?)
- additional tests that should be implemented (do the tests effectively assure that it
  works correctly?)
- code style improvements (could the code be written more clearly?)
- Do the changes represent a change in functionality so the version number should increase? Start a discussion if so.
- As a review you can generates the same outputs from running the code

Your suggestions should be tailored to the code that you are reviewing.
Be critical and clear, but not mean. Ask questions and set actions.

2023-08-29 10:10 UTC, smithv1 requested changes

2023-08-29 10:10 UTC, smithv1 commented on src/staging/validation.py
Line 21: incomplete sentence
Could add to doc string : "masterlist contains - all post codes in the UK" if that's correct
Line 39: is the doc string correct? Maybe move get_masterlist to above check_pcs_real so they can be read together more easily

2023-08-29 10:10 UTC, smithv1 commented on src/staging/validation.py
>          are valid UK postcodes. It uses the `validate_postcode` function to
update docstring validate_postcode to validate_postcode_pattern

2023-08-29 10:10 UTC, smithv1 commented on src/staging/validation.py
> +def validate_post_col(df: pd.DataFrame, postcode_masterlist: str) -> bool:
add postcode_masterlist arg

2023-08-29 10:10 UTC, smithv1 commented on src/staging/validation.py
> +def validate_post_col(df: pd.DataFrame, postcode_masterlist: str) -> bool:
Add returns to doc string - invalid_df, unreal_df

2023-08-29 10:10 UTC, smithv1 commented on src/staging/validation.py
> +def validate_post_col(df: pd.DataFrame, postcode_masterlist: str) -> bool:
Could add comment to make distiction between invalid and unreal - what distinguishes each

2023-08-29 10:10 UTC, smithv1 commented on src/staging/validation.py
> +    """Checks if the postcodes are real against a masterlist of actual postcodes.
Update format of doc string with args etc

2023-08-29 10:10 UTC, smithv1 commented on src/staging/validation.py
> +        copydf = df.copy()
maybe do .copy() at start and call the df something like check_real_df

2023-08-29 10:10 UTC, smithv1 commented on src/staging/validation.py
>      else:
is this for making an empty df?

2023-08-29 10:10 UTC, smithv1 commented on tests/test_staging/test_validation.py
Line 21: can be deleted

2023-08-29 10:10 UTC, smithv1 commented on tests/test_staging/test_validation.py
>  def write_dict_to_toml(tmp_path, test_data_dict):
is write_dict_to_toml used, if not can be deleted?

2023-08-29 10:10 UTC, smithv1 commented on tests/test_staging/test_validation.py
>      assert validate_post_col(df_valid, fake_path)
assert on dataframes - not sure what this does

2023-08-29 10:10 UTC, smithv1 commented on tests/test_staging/test_validation.py
>      if config["global"]["postcode_csv_check"]:
Line 139: alternative name for unreal_postcodes: result_df
Line 156: Checking that none of the valid post codes are in unreal_postcodes - this is potentially a repetition of test_check_pcs_real_with_invalid_postcodes

2023-08-30 15:55 UTC, AnneONS commented on src/developer_config.yaml
> +  postcode_path: "R:/BERD Results System Development 2023/DAP_emulation/staging/postcode_validation"
please could this go in /staging/staging_qa/postcode_validation ?

2023-08-30 15:55 UTC, AnneONS commented on src/developer_config.yaml
> +  postcode_path: "/ons/rdbe_dev/inter_outputs/postcode_validation"
please could you change this to /rdbe_dev/staging/staging_qa/postcode_validation ?

2023-08-31 07:08 UTC, smithv1 approved these changes
Code looks good, tests pass and runs fine on main with expected outputs: none in invalid patterns and 227 in missing

2023-08-31 08:18 UTC, merged